CREATE DATABASE IF NOT EXISTS scraperdb;

USE scraperdb;

DROP TABLE IF EXISTS news;

DROP TABLE IF EXISTS videos;

CREATE TABLE news
(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) DEFAULT NULL,
    description TEXT,
    thumbnail VARCHAR(255) DEFAULT NULL,
    link VARCHAR(255) DEFAULT NULL,
    publish_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT UQ_News_Title UNIQUE (title)
) AUTO_INCREMENT = 1;

CREATE TABLE videos
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) DEFAULT NULL,
    description TEXT,
    thumbnail VARCHAR(255) DEFAULT NULL,
    link VARCHAR(255) DEFAULT NULL,
    publish_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT UQ_Videos_Title UNIQUE (title)
) AUTO_INCREMENT = 1;
